apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-db
  name: flask-db
spec:
  ports:
  - name: "4002"
    port: 4002
    targetPort: 4002
  selector:
    io.kompose.service: flask-db
status:
  loadBalancer: {}
