apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-db
  name: flask-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: flask-db
    spec:
      volumes:
      - name: ssh-keys-vol
        persistentVolumeClaim:
          claimName: ssh-keys-vol-claim
      - name: server-uris-vol
        persistentVolumeClaim:
          claimName: server-uris-vol-claim
      containers:
      - env:
        - name: CELERY_BROKER_URL
          value: pyamqp://ensprod:ensprod@rabbit:5672
        - name: CELERY_RESULT_BACKEND
          value: rpc://ensprod:ensprod@rabbit:5672
        - name: HIVE_URI
          value: ${DB_HIVE_URI}
        - name: SERVER_URIS_FILE
          value: /server_uris/${SERVER_URIS_FILE}
        image: ensembl_prodinf/db_app
        name: flask-db
        imagePullPolicy: Never
        ports:
        - containerPort: 4002
        resources: {}
        volumeMounts:
        - mountPath: /ssh_keys
          name: ssh-keys-vol
        - mountPath: /server_uris
          name: server-uris-vol
      restartPolicy: Always
status: {}
