kind: PersistentVolume
apiVersion: v1
metadata:
  name: server-uris-persistentvol
  labels:
    type: local
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/scratch/server_uris"