kind: PersistentVolume
apiVersion: v1
metadata:
  name: ssh-keys-persistentvol
  labels:
    type: local
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/scratch/ssh_keys"